name: hanime_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  collection: ^1.18.0
  fluttertoast: ^8.2.6
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# flutter_native_splash:
#   image: assets/hanime_light.png
#   image_dark: assets/hanime_dark.png
#   web: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/locales/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
